.PHONY: clean All

All:
	@echo "----------Building project:[ ChallengeAssignement - Debug ]----------"
	@cd "ChallengeAssignement" && "$(MAKE)" -f  "ChallengeAssignement.mk"
clean:
	@echo "----------Cleaning project:[ ChallengeAssignement - Debug ]----------"
	@cd "ChallengeAssignement" && "$(MAKE)" -f  "ChallengeAssignement.mk" clean
